# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0009_auto_20170206_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Address')),
            ],
        ),
    ]
