# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateField()),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.Address'),
        ),
        migrations.AddField(
            model_name='churchmembership',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.Church'),
        ),
        migrations.AddField(
            model_name='churchmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='members',
            field=models.ManyToManyField(through='churches.ChurchMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
