# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_auto_20170628_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmembership',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='churchmembership',
            name='title',
            field=models.CharField(default='Member', max_length=250),
        ),
    ]
