# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_auto_20170628_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchmembership',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='churches.Church'),
        ),
    ]
