# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20170227_0757'),
        ('churches', '0005_auto_20170703_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='blacklist',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
